version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "TwentyFourMinutes"
  
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    assignees:
      - "TwentyFourMinutes"
