name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src/Venflow/Venflow

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/Venflow/Venflow

    - name: Configure PostgreSQL
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13.1'
        postgresql db: 'venflow_tests'
        postgresql user: 'venflow_tests'
        postgresql password: 'venflow_tests'
      shell: bash
      run: |
        export VENFLOW_TESTS_CONNECTION_STRING=Server=127.0.0.1;Port=5432;Database=venflow_tests;UserId=venflow_tests;Password=venflow_tests

    - name: Execute Tests
      working-directory: ./src/Venflow/Venflow.Tests
      run: |
        dotnet test -c Release --no-build --no-restore --verbosity normal -f net5.0