name: Publish to NuGet
on:
  push:
    branches:
      - dev
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-preview.5.21302.13

      - name: build Venflow.Generators
        working-directory: ./src/Venflow/Venflow.Generators
        run: dotnet build -c Release

      - name: Generate build directory
        working-directory: ./
        run: mkdir build

      - name: Publish Venflow.Keys on version change
        id: publish_venflow_keys_nuget
        uses: Rebel028/publish-nuget@v2.6.3
        with:
          PROJECT_FILE_PATH: src/Venflow/Venflow.Keys/Venflow.Keys.csproj
          VERSION_FILE_PATH: src/Venflow/Directory.Build.props
          PACKAGE_NAME: Venflow.Keys
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org

      - name: Publish Venflow on version change
        id: publish_venflow_nuget
        uses: Rebel028/publish-nuget@v2.6.3
        with:
          PROJECT_FILE_PATH: src/Venflow/Venflow/Venflow.csproj
          VERSION_FILE_PATH: src/Venflow/Directory.Build.props
          PACKAGE_NAME: Venflow
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org

      - name: Publish Venflow.Extensions.Logging on version change
        id: publish_venflow_extensions_logging_nuget
        uses: Rebel028/publish-nuget@v2.6.3
        with:
          PROJECT_FILE_PATH: src/Venflow/Venflow.Extensions.Logging/Venflow.Extensions.Logging.csproj
          VERSION_FILE_PATH: src/Venflow/Directory.Build.props
          PACKAGE_NAME: Venflow.Extensions.Logging
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org

      - name: Publish Venflow.AspNetCore on version change
        id: publish_venflow_aspnetcore_nuget
        uses: Rebel028/publish-nuget@v2.6.3
        with:
          PROJECT_FILE_PATH: src/Venflow/Venflow.AspNetCore/Venflow.AspNetCore.csproj
          VERSION_FILE_PATH: src/Venflow/Directory.Build.props
          PACKAGE_NAME: Venflow.AspNetCore
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org

      - name: Publish Venflow.NewtonsoftJson on version change
        id: publish_venflow_newtonsoftjson_nuget
        uses: Rebel028/publish-nuget@v2.6.3
        with:
          PROJECT_FILE_PATH: src/Venflow/Venflow.NewtonsoftJson/Venflow.NewtonsoftJson.csproj
          VERSION_FILE_PATH: src/Venflow/Directory.Build.props
          PACKAGE_NAME: Venflow.NewtonsoftJson
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
